---
# Centos SELinux setting
# sudo setsebool haproxy_connect_any on

- name: Copy haproxy.cfg
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    force: true
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart haproxy

- name: Start and enable haproxy
  ansible.builtin.systemd:
    enabled: true
    name: haproxy
    state: started
  tags:
    - systemd-service